osx_image: xcode11.3
language: objective-c
sudo: required
before_install:
  - cd ./Findout
branches:
 only:
   - develop
   - master
install:
- /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
- pod install
- brew install libsodium
- bundle install
notifications:
  email:
    recipients:
      - esgi.dev.moc@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then bundle exec fastlane ios discord_notification; fi
  - echo 'Building Findout app - iOS'
    #
    # - if [ "$TRAVIS_BRANCH" = "master" ];
    #  then bundle exec fastlane ios code_cov;
    #  then bundle exec fastlane ios discord_notification;
    #  then bundle exec fastlane ios email_notification;
    #  then bundle exec fastlane ios screenshots;
    #  then bundle exec fastlane ios beta_testflight; fi
