source "https://rubygems.org"

gem "fastlane"
gem "cocoapods"
gem "twitter"
gem 'discordrb', '~> 3.3'
gem "rake"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
