# Uncomment the lines below you want to change by removing the # in the beginning

# 1 - A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max",
  "iPhone 11 Pro",
  "iPhone 8"
])

# 2 - A list of supported languages
languages([
  'fr-FR',
  'en-EN'
])

# 3 - The name of the scheme which contains the UI Tests
scheme("Findout")

localize_simulator (true)

# 4 - Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# 5 - Clears previous screenshots
clear_previous_screenshots(true)
