# Uncomment the lines below you want to change by removing the # in the beginning

# 1 - A list of devices you want to take the screenshots from
devices([
   "iPhone 11 Pro Max"
])

# 2 - A list of supported languages
languages([
  'fr-FR',
  'en-EN'
])

# 3 - The name of the scheme which contains the UI Tests
scheme("Findout")
localize_simulator (true)
# 4 - Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# 5 - Clears previous screenshots
clear_previous_screenshots(true)


# A list of devices you want to take the screenshots from
# devices([
#   "iPhone 8",
#   "iPhone 8 Plus",
#   "iPhone SE",
#   "iPhone X",
#   "iPhone X max pro",
# ])

# languages([
#   "en-US",
#   "fr-FR",
# ])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
